apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: madazi-postgres-pvc
  namespace: madazi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
