{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: madazi-secret
  namespace: {{ include "madazi.ns" . }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  KEY_MASTER_SECRET: {{ .Values.secrets.keyMasterSecret | quote }}
  MADAZI_SVC_TOKEN: {{ .Values.secrets.svcToken | quote }}
{{- end }}
